// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package rest

// CreateScheduleRequest defines model for create_schedule_request.
type CreateScheduleRequest struct {
	// Duration days
	Duration int    `json:"duration"`
	Name     string `json:"name"`
	Period   string `json:"period"`
	UserId   int    `json:"user_id"`
}

// CreateScheduleResponse defines model for create_schedule_response.
type CreateScheduleResponse struct {
	Id int `json:"id"`
}

// ErrorResponse defines model for error_response.
type ErrorResponse struct {
	Error string `json:"error"`
}

// NextTakingResponse defines model for next_taking_response.
type NextTakingResponse struct {
	EndAt      *string `json:"end_at,omitempty"`
	Id         int     `json:"id"`
	Name       string  `json:"name"`
	NextTaking string  `json:"next_taking"`
	Period     string  `json:"period"`
}

// ScheduleResponse defines model for schedule_response.
type ScheduleResponse struct {
	EndAt     *string  `json:"end_at,omitempty"`
	Id        int      `json:"id"`
	Name      string   `json:"name"`
	Period    string   `json:"period"`
	Timetable []string `json:"timetable"`
}

// GetNextTakingParams defines parameters for GetNextTaking.
type GetNextTakingParams struct {
	// UserId user id
	UserId int `form:"user_id" json:"user_id"`

	// TZ timezone
	TZ *string `json:"TZ,omitempty"`
}

// GetScheduleParams defines parameters for GetSchedule.
type GetScheduleParams struct {
	// UserId user id
	UserId int `form:"user_id" json:"user_id"`

	// ScheduleId schedule id
	ScheduleId int `form:"schedule_id" json:"schedule_id"`

	// TZ timezone
	TZ *string `json:"TZ,omitempty"`
}

// GetSchedulesParams defines parameters for GetSchedules.
type GetSchedulesParams struct {
	// UserId user id
	UserId int `form:"user_id" json:"user_id"`

	// TZ timezone
	TZ *string `json:"TZ,omitempty"`
}

// PostScheduleJSONRequestBody defines body for PostSchedule for application/json ContentType.
type PostScheduleJSONRequestBody = CreateScheduleRequest
