// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"schedule/models"
)

// GetScheduleOKCode is the HTTP code returned for type GetScheduleOK
const GetScheduleOKCode int = 200

/*
GetScheduleOK OK

swagger:response getScheduleOK
*/
type GetScheduleOK struct {

	/*
	  In: Body
	*/
	Payload *models.ScheduleScheduleResponseDTO `json:"body,omitempty"`
}

// NewGetScheduleOK creates GetScheduleOK with default headers values
func NewGetScheduleOK() *GetScheduleOK {

	return &GetScheduleOK{}
}

// WithPayload adds the payload to the get schedule o k response
func (o *GetScheduleOK) WithPayload(payload *models.ScheduleScheduleResponseDTO) *GetScheduleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule o k response
func (o *GetScheduleOK) SetPayload(payload *models.ScheduleScheduleResponseDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetScheduleBadRequestCode is the HTTP code returned for type GetScheduleBadRequest
const GetScheduleBadRequestCode int = 400

/*
GetScheduleBadRequest Bad Request

swagger:response getScheduleBadRequest
*/
type GetScheduleBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.HTTPHandlerErrorResponse `json:"body,omitempty"`
}

// NewGetScheduleBadRequest creates GetScheduleBadRequest with default headers values
func NewGetScheduleBadRequest() *GetScheduleBadRequest {

	return &GetScheduleBadRequest{}
}

// WithPayload adds the payload to the get schedule bad request response
func (o *GetScheduleBadRequest) WithPayload(payload *models.HTTPHandlerErrorResponse) *GetScheduleBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule bad request response
func (o *GetScheduleBadRequest) SetPayload(payload *models.HTTPHandlerErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetScheduleInternalServerErrorCode is the HTTP code returned for type GetScheduleInternalServerError
const GetScheduleInternalServerErrorCode int = 500

/*
GetScheduleInternalServerError Internal Server Error

swagger:response getScheduleInternalServerError
*/
type GetScheduleInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.HTTPHandlerErrorResponse `json:"body,omitempty"`
}

// NewGetScheduleInternalServerError creates GetScheduleInternalServerError with default headers values
func NewGetScheduleInternalServerError() *GetScheduleInternalServerError {

	return &GetScheduleInternalServerError{}
}

// WithPayload adds the payload to the get schedule internal server error response
func (o *GetScheduleInternalServerError) WithPayload(payload *models.HTTPHandlerErrorResponse) *GetScheduleInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule internal server error response
func (o *GetScheduleInternalServerError) SetPayload(payload *models.HTTPHandlerErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
