// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"schedule/models"
)

// GetSchedulesOKCode is the HTTP code returned for type GetSchedulesOK
const GetSchedulesOKCode int = 200

/*
GetSchedulesOK OK

swagger:response getSchedulesOK
*/
type GetSchedulesOK struct {

	/*
	  In: Body
	*/
	Payload []int64 `json:"body,omitempty"`
}

// NewGetSchedulesOK creates GetSchedulesOK with default headers values
func NewGetSchedulesOK() *GetSchedulesOK {

	return &GetSchedulesOK{}
}

// WithPayload adds the payload to the get schedules o k response
func (o *GetSchedulesOK) WithPayload(payload []int64) *GetSchedulesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules o k response
func (o *GetSchedulesOK) SetPayload(payload []int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]int64, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetSchedulesBadRequestCode is the HTTP code returned for type GetSchedulesBadRequest
const GetSchedulesBadRequestCode int = 400

/*
GetSchedulesBadRequest Bad Request

swagger:response getSchedulesBadRequest
*/
type GetSchedulesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.HTTPHandlerErrorResponse `json:"body,omitempty"`
}

// NewGetSchedulesBadRequest creates GetSchedulesBadRequest with default headers values
func NewGetSchedulesBadRequest() *GetSchedulesBadRequest {

	return &GetSchedulesBadRequest{}
}

// WithPayload adds the payload to the get schedules bad request response
func (o *GetSchedulesBadRequest) WithPayload(payload *models.HTTPHandlerErrorResponse) *GetSchedulesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules bad request response
func (o *GetSchedulesBadRequest) SetPayload(payload *models.HTTPHandlerErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSchedulesInternalServerErrorCode is the HTTP code returned for type GetSchedulesInternalServerError
const GetSchedulesInternalServerErrorCode int = 500

/*
GetSchedulesInternalServerError Internal Server Error

swagger:response getSchedulesInternalServerError
*/
type GetSchedulesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.HTTPHandlerErrorResponse `json:"body,omitempty"`
}

// NewGetSchedulesInternalServerError creates GetSchedulesInternalServerError with default headers values
func NewGetSchedulesInternalServerError() *GetSchedulesInternalServerError {

	return &GetSchedulesInternalServerError{}
}

// WithPayload adds the payload to the get schedules internal server error response
func (o *GetSchedulesInternalServerError) WithPayload(payload *models.HTTPHandlerErrorResponse) *GetSchedulesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules internal server error response
func (o *GetSchedulesInternalServerError) SetPayload(payload *models.HTTPHandlerErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
