// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: schedule.proto

package schedulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Duration      uint32                 `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Period        int64                  `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScheduleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScheduleRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateScheduleRequest) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

type CreateScheduleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleReply) Reset() {
	*x = CreateScheduleReply{}
	mi := &file_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleReply) ProtoMessage() {}

func (x *CreateScheduleReply) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleReply.ProtoReflect.Descriptor instead.
func (*CreateScheduleReply) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScheduleReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTimetableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ScheduleId    int32                  `protobuf:"varint,2,opt,name=scheduleId,proto3" json:"scheduleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimetableRequest) Reset() {
	*x = GetTimetableRequest{}
	mi := &file_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimetableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimetableRequest) ProtoMessage() {}

func (x *GetTimetableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimetableRequest.ProtoReflect.Descriptor instead.
func (*GetTimetableRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimetableRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTimetableRequest) GetScheduleId() int32 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

type GetTimetableReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EndAt         int64                  `protobuf:"varint,2,opt,name=endAt,proto3" json:"endAt,omitempty"`
	Period        int64                  `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	Timetable     []int64                `protobuf:"varint,4,rep,packed,name=timetable,proto3" json:"timetable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimetableReply) Reset() {
	*x = GetTimetableReply{}
	mi := &file_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimetableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimetableReply) ProtoMessage() {}

func (x *GetTimetableReply) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimetableReply.ProtoReflect.Descriptor instead.
func (*GetTimetableReply) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimetableReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTimetableReply) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *GetTimetableReply) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *GetTimetableReply) GetTimetable() []int64 {
	if x != nil {
		return x.Timetable
	}
	return nil
}

type GetByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUserRequest) Reset() {
	*x = GetByUserRequest{}
	mi := &file_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUserRequest) ProtoMessage() {}

func (x *GetByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUserRequest.ProtoReflect.Descriptor instead.
func (*GetByUserRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *GetByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetByUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleIds   []int32                `protobuf:"varint,1,rep,packed,name=scheduleIds,proto3" json:"scheduleIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUserReply) Reset() {
	*x = GetByUserReply{}
	mi := &file_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUserReply) ProtoMessage() {}

func (x *GetByUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUserReply.ProtoReflect.Descriptor instead.
func (*GetByUserReply) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *GetByUserReply) GetScheduleIds() []int32 {
	if x != nil {
		return x.ScheduleIds
	}
	return nil
}

type GetNextTakingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextTakingsRequest) Reset() {
	*x = GetNextTakingsRequest{}
	mi := &file_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextTakingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextTakingsRequest) ProtoMessage() {}

func (x *GetNextTakingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextTakingsRequest.ProtoReflect.Descriptor instead.
func (*GetNextTakingsRequest) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *GetNextTakingsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetNextTakingsReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*GetNextTakingsReplyItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextTakingsReply) Reset() {
	*x = GetNextTakingsReply{}
	mi := &file_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextTakingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextTakingsReply) ProtoMessage() {}

func (x *GetNextTakingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextTakingsReply.ProtoReflect.Descriptor instead.
func (*GetNextTakingsReply) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *GetNextTakingsReply) GetItems() []*GetNextTakingsReplyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetNextTakingsReplyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EndAt         int64                  `protobuf:"varint,3,opt,name=endAt,proto3" json:"endAt,omitempty"`
	Period        int64                  `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	NextTaking    int64                  `protobuf:"varint,5,opt,name=nextTaking,proto3" json:"nextTaking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextTakingsReplyItem) Reset() {
	*x = GetNextTakingsReplyItem{}
	mi := &file_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextTakingsReplyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextTakingsReplyItem) ProtoMessage() {}

func (x *GetNextTakingsReplyItem) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextTakingsReplyItem.ProtoReflect.Descriptor instead.
func (*GetNextTakingsReplyItem) Descriptor() ([]byte, []int) {
	return file_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *GetNextTakingsReplyItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetNextTakingsReplyItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNextTakingsReplyItem) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *GetNextTakingsReplyItem) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *GetNextTakingsReplyItem) GetNextTaking() int64 {
	if x != nil {
		return x.NextTaking
	}
	return 0
}

var File_schedule_proto protoreflect.FileDescriptor

const file_schedule_proto_rawDesc = "" +
	"\n" +
	"\x0eschedule.proto\x12\bschedule\"w\n" +
	"\x15CreateScheduleRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\rR\bduration\x12\x16\n" +
	"\x06period\x18\x04 \x01(\x03R\x06period\"%\n" +
	"\x13CreateScheduleReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"M\n" +
	"\x13GetTimetableRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"scheduleId\x18\x02 \x01(\x05R\n" +
	"scheduleId\"s\n" +
	"\x11GetTimetableReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05endAt\x18\x02 \x01(\x03R\x05endAt\x12\x16\n" +
	"\x06period\x18\x03 \x01(\x03R\x06period\x12\x1c\n" +
	"\ttimetable\x18\x04 \x03(\x03R\ttimetable\"*\n" +
	"\x10GetByUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"2\n" +
	"\x0eGetByUserReply\x12 \n" +
	"\vscheduleIds\x18\x01 \x03(\x05R\vscheduleIds\"/\n" +
	"\x15GetNextTakingsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\x13GetNextTakingsReply\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.schedule.GetNextTakingsReplyItemR\x05items\"\x8b\x01\n" +
	"\x17GetNextTakingsReplyItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05endAt\x18\x03 \x01(\x03R\x05endAt\x12\x16\n" +
	"\x06period\x18\x04 \x01(\x03R\x06period\x12\x1e\n" +
	"\n" +
	"nextTaking\x18\x05 \x01(\x03R\n" +
	"nextTaking2\xbd\x02\n" +
	"\bSchedule\x12P\n" +
	"\x0eCreateSchedule\x12\x1f.schedule.CreateScheduleRequest\x1a\x1d.schedule.CreateScheduleReply\x12J\n" +
	"\fGetTimetable\x12\x1d.schedule.GetTimetableRequest\x1a\x1b.schedule.GetTimetableReply\x12A\n" +
	"\tGetByUser\x12\x1a.schedule.GetByUserRequest\x1a\x18.schedule.GetByUserReply\x12P\n" +
	"\x0eGetNextTakings\x12\x1f.schedule.GetNextTakingsRequest\x1a\x1d.schedule.GetNextTakingsReplyB\x18Z\x16schedule.v1;schedulev1b\x06proto3"

var (
	file_schedule_proto_rawDescOnce sync.Once
	file_schedule_proto_rawDescData []byte
)

func file_schedule_proto_rawDescGZIP() []byte {
	file_schedule_proto_rawDescOnce.Do(func() {
		file_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schedule_proto_rawDesc), len(file_schedule_proto_rawDesc)))
	})
	return file_schedule_proto_rawDescData
}

var file_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_schedule_proto_goTypes = []any{
	(*CreateScheduleRequest)(nil),   // 0: schedule.CreateScheduleRequest
	(*CreateScheduleReply)(nil),     // 1: schedule.CreateScheduleReply
	(*GetTimetableRequest)(nil),     // 2: schedule.GetTimetableRequest
	(*GetTimetableReply)(nil),       // 3: schedule.GetTimetableReply
	(*GetByUserRequest)(nil),        // 4: schedule.GetByUserRequest
	(*GetByUserReply)(nil),          // 5: schedule.GetByUserReply
	(*GetNextTakingsRequest)(nil),   // 6: schedule.GetNextTakingsRequest
	(*GetNextTakingsReply)(nil),     // 7: schedule.GetNextTakingsReply
	(*GetNextTakingsReplyItem)(nil), // 8: schedule.GetNextTakingsReplyItem
}
var file_schedule_proto_depIdxs = []int32{
	8, // 0: schedule.GetNextTakingsReply.items:type_name -> schedule.GetNextTakingsReplyItem
	0, // 1: schedule.Schedule.CreateSchedule:input_type -> schedule.CreateScheduleRequest
	2, // 2: schedule.Schedule.GetTimetable:input_type -> schedule.GetTimetableRequest
	4, // 3: schedule.Schedule.GetByUser:input_type -> schedule.GetByUserRequest
	6, // 4: schedule.Schedule.GetNextTakings:input_type -> schedule.GetNextTakingsRequest
	1, // 5: schedule.Schedule.CreateSchedule:output_type -> schedule.CreateScheduleReply
	3, // 6: schedule.Schedule.GetTimetable:output_type -> schedule.GetTimetableReply
	5, // 7: schedule.Schedule.GetByUser:output_type -> schedule.GetByUserReply
	7, // 8: schedule.Schedule.GetNextTakings:output_type -> schedule.GetNextTakingsReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schedule_proto_init() }
func file_schedule_proto_init() {
	if File_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schedule_proto_rawDesc), len(file_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schedule_proto_goTypes,
		DependencyIndexes: file_schedule_proto_depIdxs,
		MessageInfos:      file_schedule_proto_msgTypes,
	}.Build()
	File_schedule_proto = out.File
	file_schedule_proto_goTypes = nil
	file_schedule_proto_depIdxs = nil
}
