// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateScheduleRequest create schedule request
//
// swagger:model create_schedule_request
type CreateScheduleRequest struct {

	// days
	Duration int64 `json:"duration,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// period
	// Example: 1h30m
	Period string `json:"period,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this create schedule request
func (m *CreateScheduleRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create schedule request based on context it is used
func (m *CreateScheduleRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateScheduleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateScheduleRequest) UnmarshalBinary(b []byte) error {
	var res CreateScheduleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
