// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NextTakingResponse next taking response
//
// swagger:model next_taking_response
type NextTakingResponse struct {

	// end at
	// Example: 2025-04-21T22:00:00Z
	EndAt string `json:"end_at,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// next taking
	// Example: 2025-04-21T08:00:00Z
	NextTaking string `json:"next_taking,omitempty"`

	// period
	// Example: 1h30m
	Period string `json:"period,omitempty"`
}

// Validate validates this next taking response
func (m *NextTakingResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this next taking response based on context it is used
func (m *NextTakingResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NextTakingResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NextTakingResponse) UnmarshalBinary(b []byte) error {
	var res NextTakingResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
