// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ScheduleCreateScheduleResponseDTO schedule create schedule response d t o
//
// swagger:model schedule.CreateScheduleResponseDTO
type ScheduleCreateScheduleResponseDTO struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this schedule create schedule response d t o
func (m *ScheduleCreateScheduleResponseDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this schedule create schedule response d t o based on context it is used
func (m *ScheduleCreateScheduleResponseDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScheduleCreateScheduleResponseDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScheduleCreateScheduleResponseDTO) UnmarshalBinary(b []byte) error {
	var res ScheduleCreateScheduleResponseDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
